### ISSUE TITLE
Second MVP spots reviews

### ISSUE THREAD

**Issue by jHuang30** [jHuang30/airbmb#7]
3. Spots (05/31/19, 2 days)

showing the listings
display photos and amenity details

**Comment by pvulakh** [comment]
Really good work on this! A few tweaks: 
- [ ] Add border to all images on listing show
- [ ] Right now, the amenities modal fills up entire height of page. Make it smaller, add box shadow, and give it little `x` in a circle to close the modal (look at Airbnb's amenities modal!)
- [ ] Tweak margins/padding on booking form (add bottom padding to Date, have less space between Guest and 'book' button)
- [ ] Allow users to select how many guests will be staying! For now this can be a regular html `<select>` tag.
